engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "app/controllers/controller.js"
    - "app/class/invertedIndex.js"
    - "jasmine-standalone-2.5.2/spec/inverted-index-spec.js"
languages:
  JavaScript: true
exclude_paths:
- "src/coverage"
- "src/helpers/"
- "src/tests"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc.json