export const WILL_CREATE_DOCUMENT = 'WILL_CREATE_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_FAILURE = 'UPDATE_DOCUMENT_FAILURE';

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';

export const
  WILL_VIEW_SINGLE_DOCUMENT_SUCCESS = 'WILL_VIEW_SINGLE_DOCUMENT_SUCCESS';
export const VIEW_SINGLE_DOCUMENT_SUCCESS = 'VIEW_SINGLE_DOCUMENT_SUCCESS';
export const VIEW_SINGLE_DOCUMENT_FAILED = 'VIEW_SINGLE_DOCUMENT_FAILED';

export const GET_ALL_DOCUMENTS_SUCCESS = 'GET_ALL_DOCUMENTS_SUCCESS';
export const GET_ALL_DOCUMENTS_FAILED = 'GET_ALL_DOCUMENTS_FAILED';

export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const GET_QUOTE_FAILED = 'GET_QUOTE_FAILED';

export const GET_ALL_USER_DOCUMENTS_SUCCESS = 'GET_ALL_USER_DOCUMENTS_SUCCESS';
export const GET_ALL_USER_DOCUMENTS_FAILED = 'GET_ALL_USER_DOCUMENTS_FAILED';

export const WILL_CREATE_USER = 'WILL_CREATE_USER';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const WILL_SIGNIN_USER = 'WILL_SIGNIN_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';


export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const UPGRADE_USER_SUCCESS = 'UPDATE_USER_SUCESS';
export const UPGRADE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERSS_FAILED';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
